version: '2'
services:
    artbake-app:
        image: artbake
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://artbake-mariadb:3306/artbake
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=artbake-elasticsearch:9300
        ports:
            - 8080:8080
    artbake-mariadb:
        extends:
            file: mariadb.yml
            service: artbake-mariadb
    artbake-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: artbake-elasticsearch
